# Setup
title:               Diego Arriagada
tagline:             'Blog personal'
description:         'Este es el blog personal del diseñador gráfico Diego Arriagada en donde escribe sobre diversos temas de su interés.'
url:                 https://darriagada.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Diego Arriagada
  url:               https://darriagada.github.io/
  email:             darriagada6@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Misc
	  
collections:
  projects:
    output: true	  