title: Diego Arriagada
author: Diego Arriagada
email: darriagada6@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
   Soy Diego. Un diseñador gráfico.
   Te doy la bienvenida a mi pequeño rincón web donde comparto algunos de mis proyectos, opiniones que nadie preguntó y otras cosas de mi interés.

# social links
# twitter_username: jekyllrb
github_username:  darriagada
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

#permalink: /:categories/:year/:month/:day/:title
permalink: /notes/:title

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d %b, %Y"

# Collections
collections:
  work: # collection for personal blog posts
    output: true
    permalink: /work/:name  

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
